sudo: required
language: bash
services:
  - docker
before_install:
  - export PGM_NAME="docker-pi-bt-search"
script:
  - docker build -t $DOCKER_USERNAME/$PGM_NAME .
  - docker images
  - docker run -d --name $PGM_NAME -p 80:80 $DOCKER_USERNAME/$PGM_NAME
  - docker ps -a
  - docker logs $PGM_NAME
after_success:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/$PGM_NAME
